### ISSUE TITLE
Unhealthy method

### ISSUE THREAD

**Issue by diogoterremoto** [fukuiretu/nuxt-healthcheck#2]
First of all, thank you @fukuiretu for doing this.

Is there any way of adding an unhealthy method, to be used when the app is being compiled or when some main error is being thrown?

Thanks again.

**Comment by fukuiretu** [comment]
@diogoterremoto  Thanks for your comment.
I don't have a concrete image of what I want to do, but if you don't mind, please do some PR!

**Comment by fukuiretu** [comment]
@diogoterremoto You can reopen the issue if you need to.
